config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  devise_for :users
  root "jobs#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  JOB_TYPES = ["Full-time", "Part-time", "Internship", "Contract", "Freelance"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]

  def new
    @job = current_user.jobs.build
  end

  def create

    
    @job = current_user.jobs.build(job_params)
    token = params[:stripeToken]
    job_type = params[:job_type]
    job_title = params[:title]
    card_brand = params[:user][:card_brand]
    card_exp_month = params[:user][:card_exp_month]
    card_exp_year  = params[:user][:card_exp_year]
    card_last4 = params[:user][:card_last4]

    charge = Stripe::Charge.create(
      :amount => 30000,
      :currency => "usd",
      :description => job_type,
      :statement_descriptor => job_title,
      :source => token
    )

    current_user.stripe_id = charge.id
    current_user.card_brand = card_brand
    current_user.card_exp_month = card_exp_month
    current_user.card_exp_year = card_exp_year
    current_user.card_last4 = card_last4
    current_user.save!
    if @job.save
      redirect_to(jobs_path)
    else
      render('new')
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    render action: :new
  end

  def index
    if(params.has_key?(:job_type))
      @jobs = Job.where(:job_type => params[:job_type]).order("created_at desc")
    else
      @jobs = Job.all.order("created_at desc")
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      redirect_to(job_path(@job))
    else
      render('edit')
    end
  end

  def delete
  end

  private
  def job_params
    params.require(:job).permit(:title, :description, :url, :job_type, :location, :job_author, :remote_ok, :apply_url, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/index.html.erb
<h1>Welcome to <%= Rails.configuration.application_name %>!</h1>
<p class="lead">Use this document as a way to quickly start any new project by generating files, installing gems, and more. </p>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job, :html => { multipart: true}) do |f| %>
  <%= f.input :title, required: true, placeholder: "Eg: Frontend Developer" %>
  <%= f.input :apply_url, required: true %>

  <div class="row">
    <div class="col-md-3">
      <%= f.input :job_type, label: "Job Type", collection: Job::JOB_TYPES, include_blank: 'Select a Job Type',required: true %>
    </div>
    <div class="col-md-6 offset-md-1">
      <%= f.input :location, required: true, hint: 'Examples: "San Francisco, CA", "Seattle", "Anywhere"' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 offset-md-4">
      <%= f.input :remote_ok, as: :boolean, wrapper: false, label: false%>
      <span class="remote-checkbox">Work can be done remotely</span>
      <label><i class="fa fa-wifi"></i></label>
    </div>
  </div>

  <%= f.input :description, required: true, input_html: { rows: 4 } %>

  <div class="row">
    <div class="col-md-5">
      <%= f.input :job_author, required: true, label: "Company" %>
    </div>
    <div class="col-md-5">
      <%= f.input :url, required: true, label: "Company Website", placeholder: "http://www.company.com" %>
    </div>
  </div>

  <%= f.input :avatar, as: :file, input_html: { class: "mb-4" }, required: false, label: "Logo Image" %>

  <%= render('payment') %>

  <hr/>

  <button type="submit" class="btn btn-primary my-3">Submit</button>


<% end %>

app/views/jobs/_payment.html.erb
<% if !@job.persisted? %>
<!-- If the job is created by making the payment then this form should not be displayed -->
  <hr/>
  <h4>Payment</h4>
  <div class="row d-flex justify-content-center my-4">
    <div class="col-md-10 text-center">
      <div class="alert alert-info">
        All jobs cost $300 for 30 days
      </div>
    </div>
  </div>
  <div class="form-row mb-4">
    <label for="card-element">
      <b>Enter Credit or debit card</b>
    </label>
    <div id="card-element" class="mt-3 col-md-6">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>
  <% if current_user.stripe_id.present? %>
    <h5>Previously used card</h5>
    <table class="table">
      <thead  class="table-light">
        <th>Card Brand</th>
        <th>Last 4 digits</th>
        <th>Expiration Month</th>
        <th>Expiration year</th>
      </thead>
      <tbody>
        <td><%= current_user.card_brand %></td>
        <td><%= current_user.card_last4 %></td>
        <td><%= current_user.card_exp_month %></td>
        <td><%= current_user.card_exp_year %></td>
      </tbody>

    </table>
  <% end %>
    <!-- <button class="btn btn-info">Submit Payment</button> -->
<% end %>

app/views/jobs/delete.html.erb
<h1>Jobs#delete</h1>
<p>Find me in app/views/jobs/delete.html.erb</p>

app/views/jobs/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="edit-jobs-form">
      <h2>Edit Job</h2>
      <%= render('form') %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="index-jobs">
  <div class="row">
    <div class="col-md-2 categories text-center">
      <ul class="nav flex-column mt-5" id="nav">
        <li class="nav-item">
          <%= link_to("All Jobs", jobs_path, class: "nav-link job-type-nav all") %>
        </li>
        <li class="nav-item">
          <%= link_to("Internship", jobs_path(job_type: "Internship"), class: "nav-link job-type-nav internship") %>
        </li>
        <li class="nav-item">
          <%= link_to("Full-time", jobs_path(job_type: "Full-time"), class: "nav-link job-type-nav full-time") %>
        </li>
        <li class="nav-item">
          <%= link_to("Part-time", jobs_path(job_type: "Part-time"), class: "nav-link job-type-nav part-time") %>
        </li>
        <li class="nav-item">
          <%= link_to("Contract", jobs_path(job_type: "Contract"), class: "nav-link job-type-nav contract") %>
        </li>
        <li class="nav-item">
          <%= link_to("Freelance", jobs_path(job_type: "Freelance"), class: "nav-link job-type-nav freelance") %>
        </li>

      </ul>
    </div>
    <div class="col-md-10 jobs-section pt-5 pb-2">
      <% @jobs.each do |job| %>
        <div class="row">
          <div class="col-md-1 offset-md-1 text-right">
            <%= image_tag(job.avatar.url, class: "img-fluid") %>
          </div>
          <div class="col-md-7">
            <%= link_to(job.title, job_path(job), class: "job-title") %>

            <%= link_to(job.job_author, job.url, class: "job-author") %>

            <p><%= job.description.truncate(170) %></p>
          </div>
          <div class="col-md-3 text-center">
            <p class="job-type <%= job.job_type.downcase! %>"><%= job.job_type.capitalize %></p>
            <p><%= job.location %></p>
          </div>
        </div>
        <hr width="85%">
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="row">
  <div class="col-sm-10 offset-md-1">
    <div class="new-jobs-form my-5 ">
      <h3>Post new Job</h3>
      <%= render('form') %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">


<div class="row mt-5 mb-4">

  <div class="col-md-5 jobs-show-top">
    <h3><%= @job.title %></h3>
    <span class="fa fa-building-o"></span><p class="job-author"><%= @job.job_author %></p>
    <span class="fa fa-map-marker"></span><p class="job-location"><%= @job.location %></p>
  </div>
  <div class="col-md-2 offset-md-5 mt-1 text-center">
    <p class=" job-type-show job-type <%= @job.job_type.downcase! %>"><%= @job.job_type.capitalize %></p>
  </div>
</div>
<div class="row my-2">
  <div class="col-md-10 jobs-show-url">
    <h5 class="job-url-title">Job URL:</h5>
    <%= link_to(@job.apply_url, @job.apply_url, class: "job-url") %>
  </div>
</div>
<div class="row">
  <div class="col-md-12 jobs-show-description">
    <h5>Job Description:</h5>
    <p class="job-description"><%= @job.description %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-10 jobs-show-website">
    <h5 class="job-website-title">Company Website:</h5>
    <%= link_to(@job.url, @job.url, class: "job-website-url") %>
  </div>
</div>
<div class="row">
  <div class="col-md-10 my-3 remote-ok">
    <h5 >Remote OK: </h5>
    <p><%= @job.remote_ok ? 'Yes' : 'No' %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-10 jobs-show-buttons">
    <%= link_to("Back", jobs_path, class: "btn btn-outline-info") %>
    <% if user_signed_in? %>
      <% if @job.user_id == current_user.id %>
        <%= link_to("Edit Job", edit_job_path(@job), class: "btn btn-outline-warning ml-2") %>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->
    <%= javascript_include_tag 'application', "https://js.stripe.com/v2/", "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: "stripe-public-key", content: Rails.application.secrets.stripe_publishable_key %>
  </head>

  <body class="<%= yield (:body_class) %>">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="<%= root_path %>">Job Board</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to("Post Job", new_job_path, class: "nav-link new-job") %>
              </li>
              <li class="nav-item active">
                <%= link_to("Sign out", destroy_user_session_path, method: :delete, class: "nav-link") %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to("Log In", new_user_session_path, class: "nav-link") %>
              </li>
              <li class="nav-item">
                <%= link_to("Sign Up", new_user_registration_path, class: "nav-link") %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-info text-center notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="alert alert-danger text-center notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>




  <section class="section">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </section>


  <!-- <script type="text/javascript" src = "https://js.stripe.com/v2/"> -->

  <!-- </script> -->
  </body>
</html>

app/views/layouts/demo.html.erb
<!-- Old Navbar -->
 <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5"><%= Rails.configuration.application_name %></h1>
    <% end  %>
    <div class="navbar-burger burger" data-target="navbar">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
        <% if user_signed_in? %>

          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
              <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
        <% else %>
        <p class="control">
          <%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %>
        </p>
        <p class="control">
          <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%>
        </p>
        <% end %>

      </div>
    </div>
  </div>
</div>
</nav>
<!-- End of old Navbar  -->